### ISSUE TITLE
[server] Viewing a category doesn't work when not logged in

### ISSUE THREAD

**Issue by rhinodavid** [CodeForBoulder/upswyng#336]
To repro:
- log out
- Click 'Service Providers'
- Click a category (ex "Food")

Expected behavior:
Navigation to category page showing a list of resources in category

Actual behavior:
URL updates but no nav happens. Server logs:
```
Error: You must be logged in to perform this action.
    at requireLoggedIn (/Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:7907:15)
    at /Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:8198:20
    at Generator.next (<anonymous>)
    at /Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:96:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:92:12)
    at get$6 (/Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:8195:12)
    at handle_route (/Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:26771:11)
    at Array.find_route (/Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:26785:5)
    at nth_handler (/Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:29302:14)
    at /Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:29302:31
    at Array.<anonymous> (/Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:29351:4)
    at nth_handler (/Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:29302:14)
    at /Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:29302:31
    at Array.<anonymous> (/Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:29270:4)
    at nth_handler (/Users/davidwalsh/code-local/upswyng/packages/upswyng-server/__sapper__/dev/server/server.js:29302:14)
```

Looks like there's some admin check there that shouldn't be

**Comment by jacobvenable** [comment]
This has been addressed
